// solid-client/src/pages/host_share_screen/index.tsx
import { DesktopCapturerSource } from "electron";
import { JSX, createSignal } from "solid-js";
import Styles from "./host_share_screen.module.css";

// HostShareScreen is the component that contains the host's screen share.
// It is only visible to the host and it shows the game the host is sharing
// and info about the webrtc stream.
const HostShareScreen = (): JSX.Element => {
  const [time, setTime] = createSignal<string>("00:00:00");
  const [start, setStart] = createSignal<Date>(new Date());
  const [isSelectingVideo, setIsSelectingVideo] = createSignal<boolean>(false);
  const [sources, setSources] = createSignal<DesktopCapturerSource[]>([]);
  let interval: number;

  // updateTime is a function that gets a new date and update the time.
  // based on the difference between the new date and the start date.
  const updateTime = (): void => {
    let date = new Date();
    date = new Date(date.getTime() - start().getTime());
    setTime(date.toISOString().substring(11, 19));
  };

  // shareScreen is a function that will get from electron the
  // app availables for sharing and will put a modal in the screen
  // so the user can choose
  const shareScreen = async (): Promise<void> => {
    clearInterval(interval);
    let srcs: DesktopCapturerSource[] =
      await window.capture.getAvailableWindows();
    setSources(srcs);
    setIsSelectingVideo(true);
  };

  // shareScreen is a function that will set the app that
  // is going to be shared, and start the timer in the ui
  const handleStream = async (sourceId: string) => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: false,
        video: {
          mandatory: {
            chromeMediaSource: "desktop",
            chromeMediaSourceId: sourceId,
            minWidth: 1280,
            maxWidth: 1280,
            minHeight: 720,
            maxHeight: 720,
          },
        },
      });

      let videoTag = document.getElementById("video-host");

      videoTag.srcObject = stream;
      videoTag.onloadedmetadata = () => videoTag.play();

      setStart(new Date());
      interval = window.setInterval(updateTime, 1000);
    } catch (e) {
      console.error(e, "error in handleStream, host_share_screen");
    }
    setIsSelectingVideo(false);
  };

  return (
    <div class={Styles.page}>
      <nav class={Styles.navbar}>
        <div class={Styles.leftBar}>
          <div>☃️</div>
          <h2 class={Styles.leftBarTitle}>Ice Man | Session time: {time()}</h2>
        </div>
        <button class={Styles.rightBar} onClick={() => shareScreen()}>
          Share Screen
        </button>
      </nav>
      <div class={Styles.content}>
        <div class={Styles.screen}>
          <video id="video-host" controls class={Styles.recording} />
        </div>
        <div class={Styles.info}></div>
      </div>
      {isSelectingVideo() && (
        <div class={Styles.modal}>
          <div class={Styles.modalContent}>
            {sources().map((source) => (
              <button
                class={Styles.modalItem}
                onClick={() => handleStream(source.id)}
              >
                {source.name}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default HostShareScreen;

// client/src/pages/host_share_screen.tsx
import { useCallback, useEffect, useState } from "react";

// HostShareScreen is the component that contains the host's screen share.
// It is only visible to the host and it shows the game the host is sharing
// and info about the webrtc stream.
const HostShareScreen = (): React.ReactElement => {
  // time is a string that represents the time since the host started the session.
  // start is the time when the host started the session.
  const [time, setTime] = useState<string>("00:00:00");
  const [start] = useState<Date>(new Date());

  // updateTime is a function that will get a new date and update the time.
  // based on the difference between the new date and the start date.
  const updateTime = useCallback(() => {
    let date = new Date();
    date = new Date(date.getTime() - start.getTime());
    setTime(date.toISOString().substring(11, 19));
  }, [start]);

  // update the time every second.
  useEffect(() => {
    const interval = setInterval(updateTime, 1000);
    return () => clearInterval(interval);
  }, [updateTime]);

  return (
    <div className="host-share-screen">
      <nav className="host-share-screen__bar">
        <div className="host-share-screen__bar__left">
          <div className="host-share-screen__bar__left__logo">☃️</div>
          <h2 className="host-share-screen__bar__left__title">
            Ice Man | Session time: {time}
          </h2>
        </div>
        {/*
        <div className="host-share-screen__bar__right">
          <div className="host-share-screen__bar__right__button">End Game</div>
        </div>
        */}
      </nav>
      <div className="host-share-screen__content">
        <div className="host-share-screen__content__screen">
          <div className="host-share-screen__content__screen_recording">
          </div>
        </div>
        <div className="host-share-screen__content__info">
        </div>
      </div>
    </div>
  );
};

export default HostShareScreen;
